#!/bin/bash

echoFun(){
    str=$1
    color=$2
    case $color in
        ok)
            echo -e "\033[32m $str \033[0m"
        ;;
        err)
            echo -e "\033[31m $str \033[0m"
        ;;
        tip)
            echo -e "\033[34m $str \033[0m"
        ;;
        *)
            echo "$str"
        ;;
esac
}

helpFun(){
    echoFun "操作:" tip
    echoFun "  start       启动服务" ok
    echoFun "  stop        停止服务" ok
    echoFun "  restart     重载服务" ok
    echoFun "  reload      热重载服务" ok
    echoFun "  help        查看命令的帮助信息" ok
    echo ""
    echoFun "有关某个操作的详细信息 请使用 help 命令查看!" err
    exit 0
}

if [ "$1" == "help" ]; then
    helpFun
elif [ ! -n "$1" ]; then
    helpFun
fi

CURRENT_COMMAND=$0
SERVER_NAME=$1

psFun(){
    echoFun "-------------------------------------Process------------------------------------------" err
    ps axuw|head -1;ps axuw|grep "${SERVER_NAME}"|grep -v -E "grep|${CURRENT_COMMAND}"
    echoFun "-------------------------------------Process------------------------------------------" err
}

startFun(){
    composer dump-autoload -a
    sleep 1
    php easyswoole start d
    sleep 1
    psFun
    echoFun "Info: Server started!" ok
}

stopFun(){
    psFun
    sleep 1
    php easyswoole stop
    echoFun "Info: Server stoped!" ok
}

reloadFun(){
    IS_ALL=$1
    if [ "$IS_ALL" == "all" ]; then
        php easyswoole reload all
     else
        php easyswoole reload
    fi
    sleep 1
    psFun
    if [ "$IS_ALL" == "all" ]; then
        echoFun "Info: Server all reloaded!" ok
     else
        echoFun "Info: Server reloaded!" ok
    fi

}

case $2 in
        start)
            startFun
        ;;
        stop)
            stopFun
        ;;
        restart)
            stopFun
            startFun
        ;;
        reload)
            reloadFun $3
        ;;
        *)
            helpFun
        ;;
esac
exit 0
