#!/bin/bash

echoFun(){
    str=$1
    color=$2
    case $color in
        ok)
            echo -e "\033[32m $str \033[0m"
        ;;
        err)
            echo -e "\033[31m $str \033[0m"
        ;;
        tip)
            echo -e "\033[34m $str \033[0m"
        ;;
        *)
            echo "$str"
        ;;
esac
}

helpFun(){
    echoFun "操作:" tip
    echoFun "  start       启动服务" ok
    echoFun "  stop        停止服务" ok
    echoFun "  restart     重载服务" ok
    echoFun "  reload      热重载服务" ok
    echoFun "  help        查看命令的帮助信息" ok
    echo ""
    echoFun "有关某个操作的详细信息 请使用 help 命令查看!" err
    exit 0
}

args0=$0
args1=$1
args2=$2

if [ "$args1" == "help" ]; then
    helpFun
elif [ ! -n "$args1" ]; then
    helpFun
fi

if [ ! -n "$args2" ]; then
    args2=dev
fi

echoFun "Info: Runmode [${args2}]!" ok

basepath=$(cd `dirname $0`; pwd)
runmodeFile=${basepath}/${args2}.php

if [ ! -e $runmodeFile ];then
    echoFun "Error: Runmode file does not exits!" err
    exit 0
fi

serverName=$(cat $runmodeFile | grep 'SERVER_NAME' | awk -F "'" '{print $4}')

if [ ! -n "$serverName" ]; then
    echoFun "Error: ServerName is empty" err
    exit 0
fi

echoFun "Info: ServerName [${serverName}]!" ok

psFun(){
    echoFun "-------------------------------------Process------------------------------------------" err
    ps axuw|head -1;ps axuw|grep "${serverName}"|grep -v grep|grep -v "${args0}"
    echoFun "-------------------------------------Process------------------------------------------" err
}

startFun(){
    composer dump-autoload -a
    php easyswoole start d $args2
    echoFun "Ok: Server started!" ok
}

stopFun(){
    php easyswoole stop
    echoFun "Ok: Server stoped!" ok
}

reloadAllFun(){
    php easyswoole reload all
    sleep 1
    psFun
    echoFun "Ok: Server all reloaded!" ok
}

case $args1 in
        status)
            psFun
        ;;
        start)
            startFun
        ;;
        stop)
            stopFun
        ;;
        restart)
            stopFun
            sleep 2
            startFun
        ;;
        reload)
            reloadAllFun
        ;;
        *)
            helpFun
        ;;
esac
exit 0
