<?php
/**
 * Created by PhpStorm.
 * User: zhongyongbiao
 * Date: 2018/10/26
 * Time: 下午12:49
 */

namespace App\Controller\Http;

use EasySwoole\EasySwoole\Config;
use EasySwoole\EasySwoole\ServerManager;
use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Http\Message\Status;

abstract class Base extends Controller
{
    public function index()
    {
        // TODO: Implement index() method.
        $this->actionNotFound();
    }

    protected function actionNotFound(?string $action): void
    {
        // TODO: Change the autogenerated stub
        $this->writeJson(Status::CODE_NOT_FOUND, null, 'Action ' . $this->request()->getUri()->__toString() . ' not found');
    }

    private function getDebugData(): array
    {
        // 从请求里获取之前增加的时间戳
        $reqTime = $this->request()->getAttribute('request_time');
        // 计算一下运行时间
        $runTime = round(microtime(true) - $reqTime, 6) . 's';
        // 获取用户IP地址
        $ip = ServerManager::getInstance()->getSwooleServer()->connection_info($this->request()->getSwooleRequest()->fd);
        $ip = isset($ip['remote_ip']) ? $ip['remote_ip'] : 'unknow';
        // 拼接日志内容
        $debugInfo = ['ip' => $ip, 'now' => date('Y-m-d H:i:s'), 'runtime' => $runTime, 'uri' => $this->request()->getUri()->__toString()];
        $userAgent = $this->request()->getHeader('user-agent');
        if (is_array($userAgent) && count($userAgent) > 0) {
            $debugInfo['user_agent'] = $userAgent[0];
        }
        return $debugInfo;
    }

    protected function writeJson($statusCode = 200, $data = null, $msg = null)
    {
        if (!$this->response()->isEndResponse()) {
            if (is_null($msg)) {
                $msg = Status::getReasonPhrase($statusCode);
            }
            $data = ['code' => $statusCode, 'data' => $data, 'msg' => is_null($msg) ? '' : $msg];
            // debug 模式下多返回一些信息
            if (Config::getInstance()->getConf('app.debug') || intval($this->request()->getRequestParam('debug')) === 1) {
                $data['debug'] = $this->getDebugData();
            }
            $this->response()->write(json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
            $this->response()->withHeader('Content-type', 'application/json;charset=utf-8');
            $this->response()->withStatus($statusCode);
            return true;
        } else {
            return false;
        }
    }
}